from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome(executable_path="D:\Drivers\chromedriver.exe")
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("http://www.indianrail.gov.in/")
link_to_page = driver.find_element_by_link_text('Reserved Train Between Stations')
link_to_page.click()
time.sleep(8)
#minimize_ad = driver.find_element_by_id('corover-close-cb-btn')
#minimize_ad.click()
close_ad = driver.find_element_by_id('corover-close-btn')
close_ad.click()
date_picker = driver.find_element_by_xpath('//*[@class="ui-datepicker-trigger"]')
date_picker.click()
#driver.find_element_by_xpath('//*[@class="ui-icon ui-icon-circle-triangle-e"]').click()
driver.find_element_by_link_text('30').click()
source = driver.find_element_by_id('sourceStation')
source.send_keys('PUNE')
source.send_keys(Keys.ARROW_DOWN)
source.send_keys(Keys.ENTER)
dest = driver.find_element_by_id('destinationStation')
dest.send_keys('KYN')
time.sleep(2)
dest.send_keys(Keys.ARROW_DOWN)
dest.send_keys(Keys.ENTER)
driver.find_element_by_id('modal1').click()
time.sleep(2)
driver.find_element_by_id('inputCaptcha').send_keys('2343fdsxcv')
driver.find_element_by_id('test').click()
time.sleep(7)
driver.quit()